# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

# The `service` block is the name of the service
service: ideonline

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: nodejs6.10
  region: eu-west-2

plugins:
  - serverless-s3-sync
  - serverless-hooks-plugin

#resources:
#  Resources:
#    Bucket:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: ideonline.net
#        AccessControl: PublicRead
#        WebsiteConfiguration:
#          IndexDocument: index.html

custom:
  hooks:
    before:package:createDeploymentArtifacts:
      - yarn run build-prod
  s3Sync:
    - bucketName: ideonline.net
#      bucketPrefix: assets/ # optional
      localDir: dist
